/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_daimaqiao_xlog_decode_java_XlogDecode */

#ifndef _Included_com_github_daimaqiao_xlog_decode_java_XlogDecode
#define _Included_com_github_daimaqiao_xlog_decode_java_XlogDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_daimaqiao_xlog_decode_java_XlogDecode
 * Method:    decodeXlog
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_daimaqiao_xlog_1decode_1java_XlogDecode_decodeXlog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
